confluent_setup:
  api_key: G6D3CLLKS6Y3AD5E
  secret: 
  server: pkc-wzjyjg.us-east-2.aws.confluent.cloud:9092
table_setup:
  historical_turbine_status:
    comment: Turbine status to be used as label in our predictive maintenance model
      (to know which turbine is potentially faulty)
    confluentTopic: historical-turbine-status
    schema: '

      abnormal_sensor STRING,

      end_time LONG,

      start_time LONG,

      turbine_id STRING,

      UPDATE_TS BIGINT

      '
  parts:
    comment: Turbine parts from our manufacturing system
    confluentTopic: parts
    expectation: ADD EXPECTATION
    schema: '

      NSN STRING,

      height LONG,

      production_time LONG,

      sensors ARRAY<STRING>,

      stock_available LONG,

      stock_location STRING,

      type STRING,

      weight LONG,

      width LONG,

      UPDATE_TS BIGINT

      '
  ship_meta:
    comment: hip to turbine Meta_Data mapping
    confluentTopic: ship-meta
    schema: '

      homeport STRING,

      lat STRING,

      long STRING,

      model STRING,

      ship STRING,

      turbine_id STRING,

      UPDATE_TS BIGINT

      '
  turbine:
    comment: Turbine details, with location, wind turbine model type etc
    confluentTopic: turbine
    schema: '

      country STRING,

      lat STRING,

      location STRING,

      long STRING,

      model STRING,

      state STRING,

      turbine_id STRING,

      UPDATE_TS BIGINT

      '
